version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-app
    container_name: laravel-app
    platform: linux/amd64
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: app
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-app
    depends_on:
      - pgsql
      - pgsql_tests
      - redis
      - mailhog
    extra_hosts:
      - "host.docker.internal:host-gateway"

  scheduler:
    image: laravel-app
    container_name: laravel-scheduler
    platform: linux/amd64
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: scheduler
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-app
    depends_on:
      - app
      - pgsql
      - redis

  horizon:
    image: laravel-app
    container_name: laravel-horizon
    platform: linux/amd64
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: horizon
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-app
    depends_on:
      - app
      - pgsql
      - redis

  pgsql:
    image: postgres:15
    container_name: laravel-pgsql
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - laravel-app

  pgsql_tests:
    image: postgres:16
    container_name: laravel-pgsql-tests
    platform: linux/amd64
    ports:
      - '${DB_TEST_PORT:-5433}:5432'
    environment:
      PGPASSWORD: 'laravel_templates_tests'
      POSTGRES_DB: 'laravel_templates_tests'
      POSTGRES_USER: 'laravel_templates_tests'
      POSTGRES_PASSWORD: 'laravel_templates_tests'
    volumes:
      - 'pgsql_tests:/var/lib/postgresql/data'
    networks:
      - laravel-app

  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel-mailhog
    platform: linux/amd64
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - laravel-app

  redis:
    image: redis:7
    container_name: laravel-redis
    platform: linux/amd64
    networks:
      - laravel-app
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis:/data

networks:
  laravel-app:
    driver: bridge

volumes:
  pgsql:
    driver: local
  pgsql_tests:
    driver: local
  redis:
    driver: local
